### ISSUE TITLE
How to interpret the relative importance of sensitivity analysis results

### ISSUE THREAD

**Issue by 857687671** [hollorol/RBBGCMuso#16]
Hello, I would like to know whether there are some criteria to judge the relative importance of sensitivity analysis results.   that is, if the value of the analysis results is greater than a certain value, it can be judged that the parameter is a sensitivity parameter. For example, if the analysis result is more than 10%, it can be determined that the parameter is sensitive, and the next step of parameter optimization process is needed. Thank you.

**Comment by hollorol** [comment]
Hello,

This is one weakness of these kind of methods. The threshold is subjective. As a rule of thumb I would take into account that the calibration will be longer if you chose more parameter. If I am able to run a calibration with 10^6 iteration, I would say 6-10 parameter is the maximum I can calibrate; therefore I would select the top 6 most important variable. Another method for choose is to select the minimum percentage of variance you are Ok with. For example If I have 10 parameters and the top 4 of them account for 90% of variables, I can leave the rest because they have little impact, and I throw away only 10 percent of the total variance. 

I'll will implement a method which is less subjective (most of the feature selection methods are subjective).

**Comment by 857687671** [comment]
Hello, thanks for your detailed explanation, which is very helpful to me. Looking forward to the release of your new method.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hollorol/RBBGCMuso"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hollorol/RBBGCMuso] How to interpret the relative importance of sensitivity analysis results (#16)





 
Hello,
 
This is one weakness of these kind of methods. The threshold is subjective. As a rule of thumb I would take into account that the calibration will be longer if you chose more parameter. If I am able to run a calibration with 10^6 iteration, I would say 6-10 parameter is the maximum I can calibrate; therefore I would select the top 6 most important variable. Another method for choose is to select the minimum percentage of variance you are Ok with. For example If I have 10 parameters and the top 4 of them account for 90% of variables, I can leave the rest because they have little impact, and I throw away only 10 percent of the total variance.
 
I'll will implement a method which is less subjective (most of the feature selection methods are subjective).
